import React, { useState } from "react";
import type { ThemeConfig } from "./types";

const DEFAULT_THEME: ThemeConfig = {
  name: "matrix",
  background: "dark",
  groups: {
    Normal:  { fg: "#00ff5f", bg: "#000000" },
    Comment: { fg: "#008700", bg: "#000000" },
    String:  { fg: "#00ffaf", bg: "#000000" },
    Keyword: { fg: "#00ffff", bg: "#000000" },
    Function:{ fg: "#00ff5f", bg: "#000000" },
    Type:    { fg: "#00ff5f", bg: "#000000" },
    LineNr:  { fg: "#006b3b", bg: "#000000" },
    StatusLine:   { fg: "#000000", bg: "#00ff5f" },
    StatusLineNC: { fg: "#008700", bg: "#000000" },
  },
};

const PRESET_THEMES: Record<string, ThemeConfig> = {
    matrix: DEFAULT_THEME,
    elfish: {
    name: "elfish",
    background: "dark",
    groups: {
      Normal:  { fg: "#d0ffd0", bg: "#000000" },
      Comment: { fg: "#5f875f", bg: "#000000" },
      String:  { fg: "#afffaf", bg: "#000000" },
      Keyword: { fg: "#87d7ff", bg: "#000000" },
      Function:{ fg: "#ffffff", bg: "#000000" },
      Type:    { fg: "#ffffff", bg: "#000000" }, 
      LineNr:  { fg: "#5f875f", bg: "#000000" },
      StatusLine:   { fg: "#000000", bg: "#87ff5f" },
      StatusLineNC: { fg: "#5f875f", bg: "#000000" },
    },
  },
  desertish: {
    name: "desertish",
    background: "dark",
    groups: {
      Normal:  { fg: "#f8f8f2", bg: "#1c1c1c" },
      Comment: { fg: "#808080", bg: "#1c1c1c" },
      String:  { fg: "#ffd787", bg: "#1c1c1c" },
      Keyword: { fg: "#ffaf5f", bg: "#1c1c1c" },
      Function:{ fg: "#ffffaf", bg: "#1c1c1c" },
      Type:    { fg: "#ffffaf", bg: "#1c1c1c" },
      LineNr:  { fg: "#5f5f5f", bg: "#1c1c1c" },
      StatusLine:   { fg: "#1c1c1c", bg: "#ffd787" },
      StatusLineNC: { fg: "#aaaaaa", bg: "#262626" },
    },
  },
    gruvbox: {
    name: "gruvbox",
    background: "dark",
    groups: {
      Normal:     { fg: "#ebdbb2", bg: "#282828" },
      Comment:    { fg: "#928374", bg: "#282828" },
      String:     { fg: "#b8bb26", bg: "#282828" },
      Keyword:    { fg: "#fb4934", bg: "#282828" },
      Function:   { fg: "#fabd2f", bg: "#282828" },
      LineNr:     { fg: "#7c6f64", bg: "#282828" },
      Type:       { fg: "#fabd2f", bg: "#282828" },
      StatusLine: { fg: "#3c3836", bg: "#b8bb26" },
      StatusLineNC: { fg: "#a89984", bg: "#3c3836" },
    },
  },

  tokyonight: {
    name: "tokyonight",
    background: "dark",
    groups: {
      Normal:     { fg: "#c0caf5", bg: "#1a1b26" },
      Comment:    { fg: "#565f89", bg: "#1a1b26" },
      String:     { fg: "#9ece6a", bg: "#1a1b26" },
      Keyword:    { fg: "#bb9af7", bg: "#1a1b26" },
      Function:   { fg: "#7aa2f7", bg: "#1a1b26" }, 
      Type:       { fg: "#7aa2f7", bg: "#1a1b26" },
      LineNr:     { fg: "#414868", bg: "#1a1b26" },
      StatusLine: { fg: "#1a1b26", bg: "#7aa2f7" },
      StatusLineNC: { fg: "#a9b1d6", bg: "#24283b" },
    },
  },

  solarizedlight: {
    name: "solarizedlight",
    background: "light",
    groups: {
      Normal:     { fg: "#657b83", bg: "#fdf6e3" },
      Comment:    { fg: "#93a1a1", bg: "#fdf6e3" },
      String:     { fg: "#2aa198", bg: "#fdf6e3" },
      Keyword:    { fg: "#859900", bg: "#fdf6e3" },
      Function:   { fg: "#b58900", bg: "#fdf6e3" },
      Type:       { fg: "#b58900", bg: "#fdf6e3" },
      LineNr:     { fg: "#93a1a1", bg: "#eee8d5" },
      StatusLine: { fg: "#fdf6e3", bg: "#268bd2" },
      StatusLineNC: { fg: "#657b83", bg: "#eee8d5" },
    },
  },
};


const generateVimColorscheme = (theme: ThemeConfig): string => {
  const lines: string[] = [];

  lines.push(`" ${theme.name}.vim - generated by vim-theme-lab`);
  lines.push(`set background=${theme.background}`);
  lines.push(`hi clear`);
  lines.push(`if exists("syntax_on")`);
  lines.push(`  syntax reset`);
  lines.push(`endif`);
  lines.push(`let g:colors_name = "${theme.name}"`);
  lines.push("");

  const groups = theme.groups;

  const addGroup = (name: keyof typeof groups) => {
    const g = groups[name];
    const guiAttrs: string[] = [];
    if (g.bold) guiAttrs.push("bold");
    if (g.italic) guiAttrs.push("italic");
    if (g.underline) guiAttrs.push("underline");

    const guiAttrStr = guiAttrs.length ? ` gui=${guiAttrs.join(",")}` : "";

    lines.push(
      `hi ${name} guifg=${g.fg} guibg=${g.bg}${guiAttrStr}`
    );
  };

  addGroup("Normal");
  addGroup("Comment");
  addGroup("String");
  addGroup("Keyword");
  addGroup("Function"); 
  addGroup("Type");
  addGroup("LineNr");
  addGroup("StatusLine");
  addGroup("StatusLineNC");

  lines.push("");

  return lines.join("\n");
};


const App: React.FC = () => {
  // theme state
  const [theme, setTheme] = useState<ThemeConfig>(DEFAULT_THEME);

  // helper: deep-ish reset to default
  const resetTheme = () => {
    setTheme({
      ...DEFAULT_THEME,
      groups: { ...DEFAULT_THEME.groups },
    });
  };

  const vimScript = generateVimColorscheme(theme);

  return (
    <div className="min-h-screen flex flex-col bg-black text-emerald-400">
      {/* Header */}
      <header className="border-b border-emerald-700 px-4 py-2 flex items-center justify-between">
        <h1 className="text-lg font-bold tracking-wide">vim-theme-lab</h1>
        <span className="text-xs text-emerald-500">
          Create a custom theme for Vim
        </span>
      </header>

      {/* Main layout */}
      <main className="flex flex-1 overflow-hidden">
        {/* Vim preview panel */}
            <section className="flex-1 min-w-0 border-r border-emerald-800 p-4 overflow-auto">
            <div className="border border-emerald-700 rounded-md overflow-hidden">
            {/* top statusline */}
            <div
              className="px-2 py-1 text-xs flex justify-between"
              style={{
                color: theme.groups.StatusLine.fg,
                backgroundColor: theme.groups.StatusLine.bg,
              }}
            >
              <span>~/Code/example.py</span>
              <span>utf-8 | unix | python</span>
            </div>

            {/* code area */}
            <div
              className="px-3 py-2 text-sm font-mono leading-relaxed"
              style={{
                color: theme.groups.Normal.fg,
                backgroundColor: theme.groups.Normal.bg,
              }}
            >
              <pre className="flex">
                {/* line numbers */}
                <code
                  className="pr-4 select-none text-right"
                  style={{
                    color: theme.groups.LineNr.fg,
                    backgroundColor: theme.groups.LineNr.bg,
                  }}
                >
                  1{"\n"}2{"\n"}3{"\n"}4{"\n"}5{"\n"}6
                </code>
               
                <code className="whitespace-pre">
            
                {/* comment header */}
                <span style={{ color: theme.groups.Comment.fg }}>
                    {`# vim-theme-lab preview\n`}
                </span>
            
                <span style={{ color: theme.groups.Comment.fg }}>
                    {`# colors update live as you tweak highlight groups\n\n`}
                </span>

                {/* imports */}
                <span style={{ color: theme.groups.Keyword.fg }}>{`import `}</span>
                <span style={{ color: theme.groups.Normal.fg }}>{`time\n`}</span>
                <span style={{ color: theme.groups.Keyword.fg }}>{`from `}</span>
                <span style={{ color: theme.groups.Normal.fg }}>{`typing `}</span>
                <span style={{ color: theme.groups.Keyword.fg }}>{`import `}</span>
                <span style={{ color: theme.groups.Normal.fg }}>{`Dict, List\n\n`}</span>

                {/* config dict */}
                <span style={{ color: theme.groups.Normal.fg }}>
                    {`THEME_CONFIG: Dict[str, str] = {\n`}
                </span>
  
                <span style={{ color: theme.groups.String.fg }}>
                    {`    "name": `}
                </span>
                <span style={{ color: theme.groups.String.fg }}>
                    {`"matrix",\n`}
                </span>
                <span style={{ color: theme.groups.String.fg }}>
                    {`    "background": `}
                </span>
                <span style={{ color: theme.groups.String.fg }}>
                    {`"dark",\n`}
                </span>
                <span style={{ color: theme.groups.String.fg }}>
                    {`    "author": `}
                </span>
                <span style={{ color: theme.groups.String.fg }}>
                    {`"you",\n`}
                </span>
                <span style={{ color: theme.groups.Normal.fg }}>
                    {`}\n\n`}
                </span>

                {/* class with docstring */}
                <span style={{ color: theme.groups.Keyword.fg }}>{`class `}</span>
                <span style={{ color: theme.groups.Type?.fg || theme.groups.Function.fg }}>
    
                {`ThemePreview:\n`}
  
                </span>
                <span style={{ color: theme.groups.Normal.fg }}>{`    def __init__(self, name: str) -> None:\n`}</span>
                <span style={{ color: theme.groups.Normal.fg }}>{`        self.name = name\n`}</span>
                <span style={{ color: theme.groups.Normal.fg }}>{`        self.history: List[str] = []\n\n`}</span>
                <span style={{ color: theme.groups.Normal.fg }}>{`    def log(self, message: str) -> None:\n`}</span>
                <span style={{ color: theme.groups.String.fg }}>
                {`        """Append a message to the history and print it."""\n`}
                </span>
  
                <span style={{ color: theme.groups.Normal.fg }}>{`        timestamp = int(time.time())\n`}</span>
                <span style={{ color: theme.groups.Normal.fg }}>{`        line = f"[{timestamp}] {message}"\n`}</span>
                <span style={{ color: theme.groups.Normal.fg }}>{`        self.history.append(line)\n`}</span>
                <span style={{ color: theme.groups.Keyword.fg }}>{`        print`}</span>
                <span style={{ color: theme.groups.Normal.fg }}>{`(line)\n\n`}</span>

  
                {/* standalone function */}
                <span style={{ color: theme.groups.Keyword.fg }}>{`def `}</span>
                <span style={{ color: theme.groups.Function.fg }}>{`greet`}</span>
                <span style={{ color: theme.groups.Normal.fg }}>
                {`(name: str) -> str:\n`}
                </span>
                <span style={{ color: theme.groups.Normal.fg }}>
                {`    message = f"Hello, {name}"\n`}
                </span>
  
                <span style={{ color: theme.groups.Keyword.fg }}>{`    if `}</span>
                    <span style={{ color: theme.groups.Normal.fg }}>{`name == `}</span>
                    <span style={{ color: theme.groups.String.fg }}>{`"Neo"`}</span>
                    <span style={{ color: theme.groups.Normal.fg }}>{`:\n`}</span>
                    <span style={{ color: theme.groups.Keyword.fg }}>{`        return `}</span>
                    <span style={{ color: theme.groups.String.fg }}>
                    {`"You are the One."\n`}
                    </span>
                    <span style={{ color: theme.groups.Keyword.fg }}>{`    return `}</span>
                    <span style={{ color: theme.groups.Normal.fg }}>{`message\n\n`}</span>
  
                    {/* main block */}
                    <span style={{ color: theme.groups.Keyword.fg }}>{`if `}</span>
                        <span style={{ color: theme.groups.Normal.fg }}>{`__name__ == `}</span>
                        <span style={{ color: theme.groups.String.fg }}>{`"__main__"`}</span>
                        <span style={{ color: theme.groups.Normal.fg }}>{`:\n`}</span>
                        <span style={{ color: theme.groups.Normal.fg }}>
                            {`    preview = ThemePreview(THEME_CONFIG["name"])\n`}
                        </span>
                        
                        <span style={{ color: theme.groups.Normal.fg }}>
                            {`    preview.log(greet("Visitor"))\n`}
                        </span>
                        <span style={{ color: theme.groups.Comment.fg }}>
                            {`    # TODO: export current theme to matrix.vim\n`}
                    </span>
                </code>
           </pre>
        </div>

            {/* bottom statusline */}
            <div
              className="px-2 py-1 text-xs flex justify-between"
              style={{
                color: theme.groups.StatusLine.fg,
                backgroundColor: theme.groups.StatusLine.bg,
              }}
            >
              <span>-- INSERT --</span>
              <span>Ln 1, Col 1</span>
            </div>
          </div>
        </section>

        {/* Controls panel */}
         <aside className="w-80 max-w-xs flex-shrink-0 p-4 space-y-4 bg-black/80 border-l border-emerald-800"> 
          {/* Theme Info */}
          <div>
            <h2 className="text-sm font-semibold text-emerald-300 mb-2">
              Theme Info
            </h2>
            <div className="space-y-2 text-xs">
              <div className="flex flex-col">
                <label className="mb-1 text-emerald-500">Name</label>
                <input
                  className="bg-black border border-emerald-700 rounded px-2 py-1 text-emerald-300 text-xs focus:outline-none focus:border-emerald-400"
                  value={theme.name}
                  onChange={(e) =>
                    setTheme({ ...theme, name: e.target.value })
                  }
                />
              </div>

              {/* Revert button */}
              <button
                onClick={resetTheme}
                className="mt-2 inline-flex items-center justify-center px-2 py-1 border border-emerald-600 rounded text-emerald-300 text-xs hover:bg-emerald-900/40"
              >
                Revert to default
              </button>

                  {/* Preset selector */}
               <div className="flex flex-col mt-2">
                    <label className="mb-1 text-emerald-500">Select a Preset</label>
                <select
                    className="bg-black border border-emerald-700 rounded px-2 py-1 text-emerald-300 text-xs focus:outline-none focus:border-emerald-400"
                    value={theme.name}
                    onChange={(e) => {
                    const key = e.target.value;
                    if (key in PRESET_THEMES) {
                        const preset = PRESET_THEMES[key];
                        setTheme({
                            ...preset,
                            groups: { ...preset.groups },
                        });
                    }
                    }}
                 >
                    <option value="matrix">Matrix</option>
                    <option value="elfish">Elfish</option>
                    <option value="desertish">Desertish</option>
                    <option value="gruvbox">Gruvbox</option>
                    <option value="tokyonight">TokyoNight</option>
                    <option value="solarizedlight">Solarized Light</option>
                </select>
                </div>
            </div>
          </div>
          {/* Highlight Groups */}
          <div>
            <h2 className="text-sm font-semibold text-emerald-300 mb-2">
              Highlight Groups
            </h2>

            <div className="max-h-72 overflow-y-auto pr-2 space-y-3 border border-emerald-900/60 rounded-md p-2">
                {/* Normal */}
                <GroupControls
                  label="Normal"
                  group={theme.groups.Normal}
                onChange={(group) =>
                  setTheme({
                    ...theme,
                    groups: { ...theme.groups, Normal: group },
                    })
                }
            />

            {/* Comment */}
            <GroupControls
              label="Comment"
              group={theme.groups.Comment}
              onChange={(group) =>
                setTheme({
                  ...theme,
                  groups: { ...theme.groups, Comment: group },
                })
              }
            />

            {/* String */}
            <GroupControls
              label="String"
              group={theme.groups.String}
              onChange={(group) =>
                setTheme({
                  ...theme,
                  groups: { ...theme.groups, String: group },
                })
              }
            />

            {/* Keyword */}
            <GroupControls
              label="Keyword"
              group={theme.groups.Keyword}
              onChange={(group) =>
                setTheme({
                  ...theme,
                  groups: { ...theme.groups, Keyword: group },
                })
              }
            />

            {/* Function */}
            <GroupControls
              label="Function"
              group={theme.groups.Function}
              onChange={(group) =>
                setTheme({
                  ...theme,
                  groups: { ...theme.groups, Function: group },
                })
              }
            />

            {/* Type */}
            <GroupControls
                label="Type"
                group={theme.groups.Type}
                onChange={(group) =>
                    setTheme({
                    ...theme,
                    groups: { ...theme.groups, Type: group },
                    })
                }
            />

            {/* LineNr */}
            <GroupControls
              label="LineNr"
              group={theme.groups.LineNr}
              onChange={(group) =>
                setTheme({
                  ...theme,
                  groups: { ...theme.groups, LineNr: group },
                })
              }
            />

            {/* StatusLine */}
            <GroupControls
              label="StatusLine"
              group={theme.groups.StatusLine}
              onChange={(group) =>
                setTheme({
                  ...theme,
                  groups: { ...theme.groups, StatusLine: group },
                })
              }
            />

            {/* StatusLineNC */}
            <GroupControls
              label="StatusLineNC"
              group={theme.groups.StatusLineNC}
              onChange={(group) =>
                setTheme({
                  ...theme,
                  groups: { ...theme.groups, StatusLineNC: group },
                })
              }
            />
          </div>
          </div>


                    {/* Export panel */}
          <div>
            <h2 className="text-sm font-semibold text-emerald-300 mb-2">
              Export
            </h2>
            <p className="text-xs text-emerald-500 mb-2">
              Copy or save this into <code>~/.vim/colors/{theme.name}.vim</code> and load it with{" "}
              <code>:colorscheme {theme.name}</code>. 

              Make it permanent by adding <code>colorscheme {theme.name}</code> to your ~/.vimrc file.
            </p>

            <textarea
              className="w-full h-40 bg-black border border-emerald-700 rounded text-[11px] font-mono text-emerald-200 p-2 resize-none mb-2"
              readOnly
              value={vimScript}
            />

              <div className="flex gap-2">
    
              {/* Copy button */}
                <button
                className="inline-flex flex-1 items-center justify-center px-2 py-1 border border-emerald-600 rounded text-emerald-300 text-xs hover:bg-emerald-900/40"
                onClick={() => {
                    if (navigator.clipboard && navigator.clipboard.writeText) {
                        navigator.clipboard.writeText(vimScript).catch(() => {
                            // optional: handle error later
                        });
                    }
                }}
            >
                Copy to clipboard
                </button>

                {/* Download button */}
                <button
                    className="inline-flex flex-1 items-center justify-center px-2 py-1 border border-emerald-600 rounded text-emerald-300 text-xs hover:bg-emerald-900/40"
                    onClick={() => {
                    const blob = new Blob([vimScript], { type: "text/plain" });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement("a");
                    a.href = url;
                    a.download = `${theme.name || "theme"}.vim`;
                    document.body.appendChild(a);
                    a.click();
                    a.remove();
                    URL.revokeObjectURL(url);
                }}
                    >
                        Download .vim file
                </button>
        </div>
        </div>
        </aside>
      </main>
    </div>
  );
};

/** Small reusable control component for each highlight group */
type GroupControlsProps = {
  label: string;
  group: { fg: string; bg: string };
  onChange: (group: { fg: string; bg: string }) => void;
};

const GroupControls: React.FC<GroupControlsProps> = ({
  label,
  group,
  onChange,
}) => {
  return (
    <div className="mb-4">
      <h3 className="text-xs font-semibold text-emerald-400 mb-1">{label}</h3>

      <label className="text-xs text-emerald-500">Foreground</label>
      <input
        type="color"
        value={group.fg}
        onChange={(e) => onChange({ ...group, fg: e.target.value })}
        className="w-full h-8 cursor-pointer bg-black border border-emerald-700 rounded mb-2"
      />

      <label className="text-xs text-emerald-500">Background</label>
      <input
        type="color"
        value={group.bg}
        onChange={(e) => onChange({ ...group, bg: e.target.value })}
        className="w-full h-8 cursor-pointer bg-black border border-emerald-700 rounded"
      />
    </div>
  );
};

export default App;

